language: python
python:
    - 2.7
# command to install dependencies
before_install:
  - sudo apt-get install python-numpy
install:
  - ln -s /usr/lib/python2.7/dist-packages/numpy ~/virtualenv/python2.7/lib/python2.7/site-packages/
  - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: py.test
